### ISSUE TITLE
`docker` fact fails when docker is not installed

### ISSUE THREAD

**Issue by johanfleury** [puppetlabs/puppetlabs-docker#769]
## Describe the Bug

Since version 4.1.1, when the docker module is installed but Puppet runs on a machine without docker, facter fails with this error message:

```
Error: Facter: Error while resolving custom fact fact='docker', resolution='<anonymous>': undefined method `match?' for nil:NilClass
```

## Expected Behavior

The docker fact shouldn’t fail.

## Steps to Reproduce

1. Add puppetlabs/docker to your Puppetfile
2. Go to a machine without docker installed and run `puppet agent -t`
3. Puppet will show the following output:
```
$ puppet agent -t --environment production
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: Error while resolving custom fact fact='docker', resolution='<anonymous>': undefined method `match?' for nil:NilClass
Info: Caching catalog for foo.example.com
Info: Applying configuration version '1629995461'
Notice: Applied catalog in 6.52 seconds
```

## Environment

 - Version:
   * Puppet: 7.10.0
   * puppetlabs/docker: 4.1.1
 - Platform: Debian 10 (buster)

## Additional Context

This bug was introduced by 8ea5c52adac60489348b043fff3e26d4381bd9af where `match?` is used without checking that the return value from `Facter.value(:docker_client_version)` is not null (which it is on machines without docker installed).

**Comment by adrianiurca** [comment]
This was resolved with https://github.com/puppetlabs/puppetlabs-docker/pull/773. And will be in the next release.
